name: pedjoeang_indonesia
description: "Serious mobile game about Indonesian history for education."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.16.0
  provider: ^6.1.2
  go_router: ^13.2.0
  sizer: ^2.0.15
  image: ^4.1.7
  sqflite: ^2.3.3
  path: ^1.9.0
  flame_audio: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/menu/
    - assets/images/game/
    - assets/audio/
  fonts:
    - family: Pixeloid
      fonts:
        - asset: assets/fonts/Pixeloid-Sans.ttf
        - asset: assets/fonts/Pixeloid-SansBold.ttf
          weight: 700
    - family: PigpenCipher
      fonts:
        - asset: assets/fonts/PigpenCipher.otf

flutter_launcher_icons:
  image_path: "assets/images/icons/play_store_512.png"
  android: true
  min_sdk_android: 19
  ios: true
  remove_alpha_ios: true