name: pedjoeang_indonesia
description: "Serious mobile game about Indonesian history for education."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.16.0
  provider: ^6.1.2
  go_router: ^13.2.0
  sizer: ^2.0.15
  image: ^4.1.7
  sqflite: ^2.3.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/ui/
    - assets/images/ui/menu/
    - assets/images/ui/game/
  fonts:
    - family: Pixeloid
      fonts:
        - asset: assets/fonts/Pixeloid-Sans.ttf
        - asset: assets/fonts/Pixeloid-SansBold.ttf
          weight: 700
    - family: PigpenCipher
      fonts:
        - asset: assets/fonts/PigpenCipher.otf